[package]
name = "lsr"
version = "0.1.0"
authors = ["Ken Youens-Clark <kyclark@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
users = "0.11"

[dev-dependencies]
assert_cmd = "1"
predicates = "1"
