[package]
name = "change"
version = "0.1.0"
authors = ["Ken Youens-Clark <kyclark@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
itertools = "0.10"

[dev-dependencies]
assert_cmd = "1"
predicates = "1"
